import { integerFromString } from "FHIR/validate";

export const modelRecord = {
    "EPIC26_Q01": integerFromString,
    "EPIC26_Q02": integerFromString,
    "EPIC26_Q03": integerFromString,
    "EPIC26_Q04a": integerFromString,
    "EPIC26_Q04b": integerFromString,
    "EPIC26_Q04c": integerFromString,
    "EPIC26_Q04d": integerFromString,
    "EPIC26_Q04e": integerFromString,
    "EPIC26_Q05": integerFromString,
    "EPIC26_Q06a": integerFromString,
    "EPIC26_Q06b": integerFromString,
    "EPIC26_Q06c": integerFromString,
    "EPIC26_Q06d": integerFromString,
    "EPIC26_Q06e": integerFromString,
    "EPIC26_Q07": integerFromString,
    "EPIC26_Q08a": integerFromString,
    "EPIC26_Q08b": integerFromString,
    "EPIC26_Q09": integerFromString,
    "EPIC26_Q10": integerFromString,
    "EPIC26_Q11": integerFromString,
    "EPIC26_Q12": integerFromString,
    "EPIC26_Q13a": integerFromString,
    "EPIC26_Q13b": integerFromString,
    "EPIC26_Q13c": integerFromString,
    "EPIC26_Q13d": integerFromString,
    "EPIC26_Q13e": integerFromString,
    //"LIBID_Q01": integerFromString,
    //"LIBID_Q02": integerFromString,
    //"LIBID_Q03a": integerFromString,
    //"LIBID_Q03b": integerFromString,
    //"LIBID_Q03c": integerFromString,
    //"LIBID_Q03d": integerFromString,
    //"LIBID_Q03e": integerFromString,
}